from __future__ import annotations

import hashlib
from pathlib import Path


class OpenFOAMFileWriter:
    GENERATED_HEADER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by OpenFOAM Preprocessor. Do not edit manually.                  |
\\*---------------------------------------------------------------------------*/
"""

    @classmethod
    def write_if_changed(cls, path: Path, body: str) -> bool:
        content = cls.GENERATED_HEADER + body.rstrip() + "\n"

        if path.exists():
            old_hash = hashlib.sha256(path.read_bytes()).digest()
            new_hash = hashlib.sha256(content.encode("utf-8")).digest()
            if old_hash == new_hash:
                return False

        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(f"{path.suffix}.tmp")
        # newline="\n": bytes on disk must match the hashed content on every
        # platform, otherwise write-if-changed always rewrites on Windows.
        temporary.write_text(content, encoding="utf-8", newline="\n")
        temporary.replace(path)
        return True
