from __future__ import annotations

import hashlib
import math
from pathlib import Path


def foam_scalar(value: float) -> str:
    """Shortest round-trip representation; never truncates precision like :g."""
    number = float(value)
    if not math.isfinite(number):
        raise ValueError(f"Cannot write non-finite value {number!r} to an OpenFOAM dictionary.")
    return repr(number)


def foam_vector(x: float, y: float, z: float) -> str:
    return f"({foam_scalar(x)} {foam_scalar(y)} {foam_scalar(z)})"


def foam_header(object_name: str) -> str:
    """The FoamFile header block OpenFOAM utilities expect at the top of a dictionary."""
    return f"""\
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      {object_name};
}}
"""


class OpenFOAMFileWriter:
    GENERATED_HEADER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by OpenFOAM Preprocessor. Do not edit manually.                  |
\\*---------------------------------------------------------------------------*/
"""

    @classmethod
    def write_if_changed(cls, path: Path, body: str) -> bool:
        content = cls.GENERATED_HEADER + body.rstrip() + "\n"

        if path.exists():
            old_hash = hashlib.sha256(path.read_bytes()).digest()
            new_hash = hashlib.sha256(content.encode("utf-8")).digest()
            if old_hash == new_hash:
                return False

        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(f"{path.suffix}.tmp")
        # newline="\n": bytes on disk must match the hashed content on every
        # platform, otherwise write-if-changed always rewrites on Windows.
        temporary.write_text(content, encoding="utf-8", newline="\n")
        temporary.replace(path)
        return True

    @classmethod
    def remove_if_generated(cls, path: Path) -> bool:
        """Delete a stale file only if this application generated it."""
        if not path.is_file():
            return False
        if not path.read_text(encoding="utf-8", errors="replace").startswith(
            cls.GENERATED_HEADER
        ):
            return False
        path.unlink()
        return True
